[ 2024-06-03 17:21:50,492 ] 59 root - ERROR - 'Predictor' object has no attribute 'self' at Prediction_Pipeline.py file
